const PDFDocument = require('pdfkit');
const fs = require('fs');

// Simple test to verify PDFKit works
async function testPDFKit() {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const fileName = `test_${Date.now()}.pdf`;
      const filePath = `./${fileName}`;
      
      const writeStream = fs.createWriteStream(filePath);
      doc.pipe(writeStream);

      // Add some test content
      doc.fontSize(16).font('Helvetica-Bold');
      doc.text('PDFKit Test Document', 50, 50);
      
      doc.fontSize(12).font('Helvetica');
      doc.text('This is a test document generated by PDFKit.', 50, 100);
      doc.text('If you can see this, PDFKit is working correctly!', 50, 120);
      
      doc.text(`Generated at: ${new Date().toLocaleString()}`, 50, 150);

      doc.end();

      writeStream.on('finish', () => {
        console.log(`✅ PDFKit test successful! File created: ${fileName}`);
        // Clean up
        fs.unlink(filePath, (err) => {
          if (err) console.log('Note: Could not delete test file');
        });
        resolve(true);
      });

      writeStream.on('error', (error) => {
        console.error('❌ PDFKit test failed:', error);
        reject(error);
      });

    } catch (error) {
      console.error('❌ PDFKit test failed:', error);
      reject(error);
    }
  });
}

// Run the test
testPDFKit()
  .then(() => {
    console.log('🎉 PDFKit is ready to use!');
    process.exit(0);
  })
  .catch((error) => {
    console.error('💥 PDFKit test failed:', error);
    process.exit(1);
  }); 